/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fblumgarcia.ingresopagos;

/**
 *
 * @author fblum
 */
public class UIbotones extends javax.swing.JFrame {

    /**
     * Creates new form UIbotones
     */
    public UIbotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crearestudiante = new javax.swing.JButton();
        registropago = new javax.swing.JButton();
        semanterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Qué desea hacer?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, 50));

        crearestudiante.setBackground(new java.awt.Color(204, 255, 102));
        crearestudiante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crearestudiante.setText("Crear estudiante");
        crearestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearestudianteActionPerformed(evt);
            }
        });
        getContentPane().add(crearestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 277, 100));

        registropago.setBackground(new java.awt.Color(204, 204, 255));
        registropago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registropago.setText("Registrar Pago");
        registropago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registropagoActionPerformed(evt);
            }
        });
        getContentPane().add(registropago, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 277, 100));

        semanterior.setBackground(new java.awt.Color(153, 153, 153));
        semanterior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        semanterior.setText("Registrar otros pagos o semestres anteriores");
        semanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semanteriorActionPerformed(evt);
            }
        });
        getContentPane().add(semanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 300, 470, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registropagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registropagoActionPerformed
        UIregistroPago sc = new UIregistroPago();
        sc.setVisible(true);
    }//GEN-LAST:event_registropagoActionPerformed

    private void crearestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearestudianteActionPerformed
       UIcrearEstudiante sc = new UIcrearEstudiante();
        sc.setVisible(true);
    }//GEN-LAST:event_crearestudianteActionPerformed

    private void semanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semanteriorActionPerformed
       UIregistrosemant sc = new UIregistrosemant();
        sc.setVisible(true);
    }//GEN-LAST:event_semanteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIbotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIbotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIbotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIbotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIbotones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearestudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registropago;
    private javax.swing.JButton semanterior;
    // End of variables declaration//GEN-END:variables
}
